development:
  db:
    uri: "mongodb://localhost/elleol_development"
  facebook:
    appId: "265238776923880"
    appSecret: "afae4c41242967d8e440e24368cbbdf4"
    host_uri: "http://localhost:3000"
staging:
  db:
    uri: "mongodb://localhost/elleol_staging"
  facebook:
    appId: "265238776923880"
    appSecret: "afae4c41242967d8e440e24368cbbdf4"
    host_uri: "http://localhost:3000"
production:
  db:
    uri: "mongodb://delorenj:Iree3cam@flame.mongohq.com:27059/app5538702"
  facebook:
    appId: "419178718128096"
    appSecret: "4716f5c51f87e23ed0679feab5d6ef2a"
    host_uri: "http://www.elleol.com"
